{% set name = "flake8-rst" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9d7c42ef63da78cde1dc16d712b9eb1e0d2e4374483f7cbf4e8bc975af4d9b3f

build:
  number: 1
  noarch: python
  entry_points:
    - flake8-rst = flake8_rst.cli:main
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv '

requirements:
  host:
    - flake8 >=3.5.0
    - pip
    - python {{ python_min }}
  run:
    - flake8 >=3.5.0
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - flake8_rst
  commands:
    - flake8-rst --help

about:
  home: https://github.com/kataev/flake8-rst
  license: MIT
  license_family: MIT
   # LICENSE File currently missing from sdist. ref [PR 1](https://github.com/kataev/flake8-rst/pull/1)
  license_file: LICENSE
  summary: flake8 for code in rst files and docstrings
  doc_url: https://github.com/kataev/flake8-rst
  dev_url: https://github.com/kataev/flake8-rst

extra:
  recipe-maintainers:
    - dopplershift
    - FHaase
